/*
* This is the main landing page component of the app. I.e., It is displayed within the '/' route when the
* page is loaded.
*/

/* Import of a styled Link component that is used for the 'Search Page' button */
import {StyledPrimaryLink} from "./styled-components";

/* Import of main stylesheet generated by the SCSS files */
import '../scss/main.css';

export const LandingPage = () => {
    return (
        <div className={"landing-page"}>
            <div className={"landing-page-elements"}>
                <p>This Merriam_webster API driven website will provide word:</p>
                <ul>
                    <li>Definitions</li>
                    <li>Usages</li>
                </ul>
                {/* This links to the WordBox component which will also be displayed within the '/' route */}
                <StyledPrimaryLink to={"wordBox"} type={"button"} className={"btn-word-select"}>
                    Search Page
                </StyledPrimaryLink>
            </div>
        </div>
    )
}