import { Link } from 'react-router-dom';
import styled from "styled-components";


/* Import of main stylesheet generated by SCSS */
import '../scss/main.css';

/* Styling for styled component - wordBox route */
const StyledLink = styled(Link)`
  text-decoration: none;
  border-radius: 2rem;
  box-shadow: 1rem 1rem 3rem #000000,
-1px -1px 3rem #DEDEDE;
`

export const LandingPage = () => {
    return (
        <div className={"landing-page"}>
            <h1>Welcome to the word box</h1>
            <p>Here you can enter a word and get the:</p>
            <ul>
                <li>Definition</li>
                <li>Usage</li>
                <li>Pronunciation</li>
            </ul>
            <StyledLink to={"wordBox"} type={"button"} className={"btn-word-select"}>
                Enter a word
            </StyledLink>
        </div>
    )
}