import {StyledPrimaryLink} from "../styled-components/styled-components";


/* Import of main stylesheet generated by SCSS */
import '../scss/main.css';



export const LandingPage = () => {
    return (
        <div className={"landing-page"}>
            <h1>Welcome to the word box</h1>
            <p>Here you can enter a word and get the:</p>
            <ul>
                <li>Definition</li>
                <li>Usage</li>
                <li>Pronunciation</li>
            </ul>
            <StyledPrimaryLink to={"wordBox"} type={"button"} className={"btn-word-select"}>
                Enter a word
            </StyledPrimaryLink>
        </div>
    )
}