/*
 This is the general layout component that will be present on all pages as they are
* render via the different routes. I.e., All other routes are sub-routes of this
* component
*
*/

/* Import of module required from React-Router */
import { Outlet } from "react-router-dom";

/* Import of styled-component needed in this component */
import { StyledLink } from "./styled-components";

/* Import of main stylesheet generated by the SCSS files */
import '../scss/main.css';

/* Import of the image needed in this component */
import MWBrand from '../images/MWLogo_120x120.png';

export const Layout = () => {
    return (
        <div className={"layout"}>
            <div className={"layout-top"}>
                {/* These are styled Link components used on the navigation buttons */}
                <div className={'styled-links'}>
                    <StyledLink to={"/"}>Home</StyledLink>
                    <StyledLink to={"wordBox"}>Search</StyledLink>
                </div>
                <h1>The Word Chest</h1>
                <img src={MWBrand} alt={"Merriam-Webster Brand"}/>
            </div>
            {/* This allows this parent route to be rendered when child routes are being rendered in the UI */}
            <Outlet/>
        </div>
    )
}