import styled from "styled-components";
import { Link } from 'react-router-dom'
/* Import of main stylesheet generated by SCSS files */
import '../scss/main.css';

/* Styling for styled-component - input form field */
const StyledInput = styled.input`
  border-radius: 2rem;
  font-family: "Lato", Arial, sans-serif;
  background-color: #DEDEDE;
  border: none;
  outline: none;
  width: 60rem;
`

/* Styling for styled-component - home route */
const StyledLink = styled(Link)`
  text-decoration: none;
  border-radius: 2rem;
  box-shadow: 1rem 1rem 3rem #000000,
-1px -1px 3rem #DEDEDE;
  margin: 0 0 5rem 5rem;
  width: 10rem;
  padding: 1rem 2rem 1rem 2rem;
  text-align: center;
  background-color: #DEDEDE;
  color: #080808;
  text-transform: uppercase;
  font-size: 2rem;
  font-weight: 700;
  position: absolute;
  bottom: 1rem;
  right: 5rem;
`

/* Definition of a simple word input box component */
export const WordBox = () => {
    return (
        <div className={"word-box-container"}>
            <form className={"word-form"}>
                <label htmlFor={"word-input-box"}>Please enter a word to search</label>
                <StyledInput style={{fontSize: 24}} type={"text"} className={"word-input-box"} />
            </form>
            <StyledLink to={"/"} type={"button"}>
                Home
            </StyledLink>
        </div>
    )
}