import {StyledForm, StyledInput, StyledLabel, StyledSearchButton} from "../styled-components/styled-components";
/* Import of main stylesheet generated by SCSS files */
import '../scss/main.css';
import {useEffect, useState, useRef} from "react";
import {HomeButton} from "./HomeButton";
import {SearchResult} from "./SearchResult";


/* Definition of a simple word input box component */
export const WordBox = () => {

    const [searchWord, setSearchWord] = useState( '');
    const [dataRequest, setDataRequest] = useState(null)
    const [error, setError] = useState(null);
    const inputRef = useRef(null);

    useEffect(() => {

        const fetchURL = `https://www.dictionaryapi.com/api/v3/references/collegiate/json/${searchWord}?key=${process.env.REACT_APP_DICTIONARY_API_KEY}`;

        const fetchWord = async () => {
            try {
            const response = await fetch(fetchURL)
            const json = await response.json();
            console.log(json);
            setDataRequest(json);
            } catch (err) {
                setError(err)
                console.log(error)
            }
        }

        fetchWord().then(r => console.log(r));

        },[searchWord]);

    const onClickHandler = () => {
        setSearchWord(inputRef.current.value);
        inputRef.current.value = '';
    }

    const onPressDownHandler = (e) => {
        if(e.key === 'Enter') {
            inputRef.current.focus();
            setSearchWord(inputRef.current.value);
        }
    }

    return (
        <div className={"word-box-container"}>
            <StyledForm className={"word-form"}>
                <StyledLabel htmlFor={"word-input-box"}>Please enter a word to search</StyledLabel>
                <StyledInput
                    style={{fontSize: 24}}
                    type={"text"}
                    className={"word-input-box"}
                    ref={inputRef}
                    name={"wordInput"}
                />
                <StyledSearchButton
                    className={"btn-word-select"}
                    onClick={onClickHandler}
                    onKeyDown={onPressDownHandler}
                >
                    Search
                </StyledSearchButton>
            </StyledForm>
            <SearchResult
                error={error}
                data={dataRequest}
                searchWord={searchWord}
            />
            <HomeButton/>

        </div>
    )
}