/* Importing the BrowserRouter features needed */
import {Routes, Route} from 'react-router-dom';

/* Import of components needed in the respective routes */
import {LandingPage} from "./components/LandingPage";
import {WordBox} from "./components/WordBox";

/* Import of main stylesheet generated by the SCSS files */
import './scss/main.css';

export const App = () => {

    return (
        <div className="App">
            <Routes>
                <Route path={"/"} element={<LandingPage/>}/>
                <Route path={"wordBox"} element={<WordBox/>}/>
            </Routes>
        </div>
    );
}