/* Import of modules required in this component */
import {Routes, Route} from 'react-router-dom';

/* Import of components required in this main App component */
import {Layout} from "./components/Layout";
import {LandingPage} from "./components/LandingPage";
import {WordBox} from "./components/WordBox";
import {SearchResult} from "./components/SearchResult";

/* Import of main stylesheet generated by the SCSS files */
import './scss/main.css';
import {Error} from "./components/Error";

export const App = () => {

    return (
        /* Setup of React-Router routes for the application */
        <Routes>
            <Route path={'/'} element={<Layout/>} exact>
                <Route index element={<LandingPage/>}/>
                <Route path={'wordBox'} element={<WordBox/>}/>
                <Route path={'searchResult'} element={<SearchResult/>} exact/>
                <Route path={"errors"} element={<Error/>}/>
            </Route>
        </Routes>
    );
}