/* Import of modules required in this render */
import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from "react-router-dom";

/* Import of components needed in this render */
import { App } from './App';

/* Import of the main style sheet generated by the SCSS files */
import './scss/main.css';

/* Rendering the main component in the HTML document's div with id "root" */
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
    <React.StrictMode>
        <BrowserRouter>
            <App/>
        </BrowserRouter>
    </React.StrictMode>
);